// Conversations
export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';

// Users
export const SUBMIT_USERNAME = 'SUBMIT_USERNAME';
export const SUBMIT_USERNAME_SUCCESS = 'SUBMIT_USERNAME_SUCCESS';